---

- import_tasks: check_vars.yml

- name: "Deploy {{ chart_name }} ({{ chart_name_from_repo }}) helm chart to {{ kubernetes_namespace }}"
  block:
    - name: Create temporary values file
      tempfile:
        state: file
        suffix: .yml
      register: values_file

    - name: Populate temporary values file
      template:
        src: "{{ chart_name_from_repo | basename }}-values.yml.j2"
        dest: "{{ values_file.path }}"
      no_log: true

    - name: "Deploy and activate {{ chart_name }}"
      shell: |
        helm repo add stable {{ chart_repo }}
        helm repo update
        helm upgrade {{ chart_name }} \
          --install \
          --namespace {{ kubernetes_namespace }} \
          --values {{ values_file.path }} \
          {{ chart_name_from_repo }}
      register: helm_output
      
    - name: Remove temp file
      file:
        path: "{{ values_file.path }}"
        state: absent
  when:
    - kubernetes_namespace is defined